# Generated by Django 5.1.7 on 2025-03-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_enrollment_price_alter_membershipplan_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='FullName',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='paymentStatus',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Phone',
            field=models.CharField(default='0000000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='DOB',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=15),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Reference',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectTrainer',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='plan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Fullname',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=15),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Phone',
            field=models.CharField(default='0000000000', max_length=50),
        ),
        migrations.AddField(
            model_name='trainer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
