# Generated by Django 5.1.7 on 2025-03-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_enrollment_price_alter_enrollment_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='Fullname',
            new_name='fullname',
        ),
    ]
