# Generated by Django 5.1.7 on 2025-03-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_rename_fullname_enrollment_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='gallery')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
