# Generated by Django 5.1.7 on 2025-03-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Selectdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='phonenumber',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
